### ISSUE TITLE
audio context is sometimes not resumed correctly

### ISSUE THREAD

**Issue by angusmoncrieff** [swevans/unmute#3]
Hello @swevans, and thank you for this script (and for [your SO answers](https://stackoverflow.com/a/54833985/11571725)) which eventually got me unstuck on [my project](https://www.scale-lookup.com)!

However, I'm finding that occasionally the audio is not resumed correctly when working on Chrome on my laptop. After some investigation I think the problem is here:

```javascript
    function pageStateCheck() {
        if (isPageVisible && iosIsPageFocused) {
            if (!isPageActive) {
                isPageActive = true;
                pageActivated();
            }
        }
        else {
            if (isPageActive) {
                isPageActive = false;
                pageDeactivated();
            }
        }
    }
```
i.e. the first if condition will only be true if iosIsPageFocused is true - which looks questionable to me as that variable is clearly only relevant for ios. Of course it would be ok if that var just stayed true if we're not ios, but after much logging I find that it can become false (e.g. if the page is refreshed though its tab is not in the foreground).

So I think the fix would be something like the following:

```javascript
    function pageStateCheck() {
        if (isPageVisible && (iosIsPageFocused || !isIOS)) {
            if (!isPageActive) {
...
```
I'd really appreciate it if you were able to confirm this, or otherwise point me in the right direction.

Many thanks!

**Comment by swevans** [comment]
@gusmoney This is an incredible find. I never even considered browser tabs being reloaded in the background. I don't think your fix is the best one, but it would probably work. The issue is that the code was running an initial isFocused check whether or not the OS is iOS. I added a very small change near the bottom of unmute.ts to rectify this:
```
if (isIOS) win_focusChange(); // isIOS check is new
```

I also added support for detecting new iPads that try to appear as macs.

I'm going to leave this open for a bit to give you a chance to respond. Sorry for my slow turn around on this. I have been incredibly busy for the last few months.

**Comment by angusmoncrieff** [comment]
@swevans thanks for your response. I'm sure you would know better than I do how best to fix - but FWIW the line that I suggested changing does look confusing to me. I mean one might infer that a variable called iosIsPageFocused would only ever be true in an ios setting. To put it another way, it feels questionable to have the route through the code dependent on an ios variable when we are not in ios...?

...That's just to explain how I saw it. Of course, please address or not as you see fit (and go ahead and close this).

Thanks again for unmute!
