### ISSUE TITLE
Doesn't work on newest iPad 5th Gen with 15.2 Beta

### ISSUE THREAD

**Issue by numerized** [swevans/unmute#5]
EDITED:
I was using the older script that doesn't mute on tab change...
maybe you should include this as an option I want my sound to never be muted at all.

OLD COMMENT:
Hi there, I was successfully using your unmute script it's really awesome, tough, it is not working on newest iPad 5th Gen with 15.2 Beta.

So what I did is I removed the condition to detect if it's iOS and it works like a charm. You might consider improving the iPad iOS detection here to make the script more compatible.

BIG THANKS (you can keep the pizza donation ... only if you buy a veg pizza!)

``` if (isIOS) { } ```

**Comment by swevans** [comment]
@numerized Thanks for following up on this. And thank you for the pizza!

RE: iOS 15.2 Beta:

1. Would you mind sharing your user agent string with me? I am hesitant to update to beta on my device. 
2. When you encountered this issue- were you using the older version of unmute script? at least one of the older versions had trouble identifying new ipads. This line "(ua.indexOf("mac os x") >= 0 && navigator.maxTouchPoints > 0)" should detect newer ipads just fine. It works correctly on my iPad Pro 5th gen running 15 non-beta.

RE: adding the option to never unmute:
There are two potential issues with this.

1. Running audio constantly will abuse the user's battery. This is something for you, as the developer, to be weary of.
2. Not muting when in background will display the iOS audio playback controls on the user's lock screen / mission control / somewhere on the UI. There is absolutely no way to disable these controls on new versions of iOS. IMO- it is one of apple's many attempts to gimp web apps in order to force developers and users onto their native apps. This is again, something for you to be weary of as a developer.

I will likely be pushing an update to unmute in the near-ish future that actually improves the muting / unmuting when the app gains / loses visibility and focus. That said, I'd be happy to help you make a fork of this with modifications to never mute when in background if you still desire that even with the caveats listed above.

**Comment by swevans** [comment]
@numerized I am going to close this issue due to no response. Please note that I did push an update to unmute. I added an option to allow background playback (as you requested) and an option to force iOS behavior on any device, however I don't think it should be necessary and strongly advice against using it.
